apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-sso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.github.clientID
      remoteRef:
        key: secret/argocd/github
        property: clientID
    - secretKey: dex.github.clientSecret
      remoteRef:
        key: secret/argocd/github
        property: clientSecret