apiVersion: v2
name: arc-app
version: 0.1.0

dependencies:
  - name: gha-runner-scale-set-controller
    version: 0.11.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
  - name: gha-runner-scale-set
    version: 0.11.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts