apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: github-auth-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_app_id
      remoteRef:
        key: secret/data/arc
        property: app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: secret/data/arc
        property: installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: secret/data/arc
        property: private_key