apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: github-arc
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: controller-manager
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        github_app_id: "{{ .app_id }}"
        github_app_installation_id: "{{ .installation_id }}"
        github_app_private_key: "{{ .private_key }}"
  dataFrom:
    - extract:
        key: secret/data/arc