argo-cd:
  server:
    service:
      type: LoadBalancer

    extraArgs:
      - --insecure

  applicationSet:
    enabled: true

  configs:
    cm:
      admin.enabled: true
    
    rbac:
      policy.default: role:readonly
      policy.csv: |
        p, role:org-admin, applications, *, */*, allow
        p, role:org-admin, clusters, get, *, allow
        p, role:org-admin, repositories, *, *, allow
        p, role:org-admin, logs, get, *, allow
        p, role:org-admin, exec, create, */*, allow
        g, admin, role:org-admin

  redis:
    secret:
      create: true
      init:
        enabled: false
